# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_auto_20170918_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projeto.Pessoa')),
                ('currilo', models.TextField(max_length=50)),
            ],
            bases=('projeto.pessoa',),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
    ]
