# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_auto_20170918_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigocientifico',
            name='Autores',
            field=models.ManyToManyField(to='projeto.Autor'),
        ),
    ]
